import { afterEach, describe, expect, it } from "vitest";
import { mkdtempSync, mkdirSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { createSelfHostServer } from "../../server/node-runtime.mjs";
const cleanup: Array<() => void> = [];
async function listen(server: ReturnType<typeof import("node:http").createServer>) { await new Promise<void>((ok, fail) => { server.once("error", fail); server.listen(0, "127.0.0.1", ok); }); const address = server.address(); const base = `http://127.0.0.1:${typeof address === "object" && address ? address.port : 0}`; cleanup.push(() => server.close()); return base; }
function fixture() { const root = mkdtempSync(join(tmpdir(), "portaless-runtime-")); const functions = join(root, "functions"); const dist = join(root, "dist"); mkdirSync(join(functions, "admin", "items"), { recursive: true }); mkdirSync(join(dist, "admin"), { recursive: true }); writeFileSync(join(dist, "index.html"), "<h1>home</h1>"); writeFileSync(join(functions, "_middleware.js"), `export async function onRequest(c) { c.data.global = true; return c.next(); }`); writeFileSync(join(functions, "admin", "_middleware.js"), `export async function onRequest(c) { if (c.request.headers.get('cookie') !== 'ok=1') return Response.redirect(new URL('/login', c.request.url), 302); c.data.admin = true; return c.next(); }`); writeFileSync(join(functions, "admin", "items", "[slug].js"), `export async function onRequestGet(c) { return Response.json({ slug: c.params.slug, global: c.data.global, admin: c.data.admin }); } export async function onRequestPost() { return new Response('created', { status: 201, headers: { 'set-cookie': 'ok=1; Path=/' } }); }`); cleanup.push(() => rmSync(root, { recursive: true, force: true })); return { root, functions, dist }; }
afterEach(() => { while (cleanup.length) cleanup.pop()!(); });
describe("self-host Node runtime", () => { it("sirve estaticos, aplica middleware anidado, enruta parametros y conserva Set-Cookie", async () => { const paths = fixture(); const server = await createSelfHostServer({ rootDir: paths.root, functionsDir: paths.functions, staticDir: paths.dist, env: {} }); const base = await listen(server); expect((await fetch(base + "/")).status).toBe(200); expect(await (await fetch(base + "/")).text()).toContain("home"); const blocked = await fetch(base + "/admin/items/hola", { redirect: "manual" }); expect(blocked.status).toBe(302); expect(blocked.headers.get("location")).toBe("/login"); const allowed = await fetch(base + "/admin/items/hola", { headers: { cookie: "ok=1" } }); expect(await allowed.json()).toEqual({ slug: "hola", global: true, admin: true }); const created = await fetch(base + "/admin/items/hola", { method: "POST", headers: { cookie: "ok=1" } }); expect(created.status).toBe(201); expect(created.headers.get("set-cookie")).toContain("ok=1"); }); it("devuelve 405 con Allow, bloquea traversal y expone healthz", async () => { const paths = fixture(); const server = await createSelfHostServer({ rootDir: paths.root, functionsDir: paths.functions, staticDir: paths.dist, env: {} }); const base = await listen(server); const method = await fetch(base + "/admin/items/hola", { method: "PUT", headers: { cookie: "ok=1" } }); expect(method.status).toBe(405); expect(method.headers.get("allow")).toContain("GET"); expect((await fetch(base + "/healthz")).status).toBe(200); expect((await fetch(base + "/%2e%2e/%2e%2e/etc/passwd")).status).toBe(403); }); });
